### ISSUE TITLE
docker container run with ADDONS="senaite.patient"

### ISSUE THREAD

**Issue by noblelabs1** [senaite/senaite.docker#9]
The instance doesn't load the patient addon when I run:
 docker container run --publish 9999:8080 --detach --name NBLIMS -e ADDONS="senaite.patient" senaite .

It did however successfully load the storage addon.  

Any ideas?

**Comment by ramonski** [comment]
Hi @noblelabs1,

Try to use a compose file like this one:

```
version: "3.8"

services:

  zeo:
    container_name: zeo-mysenaite
    image: senaite/senaite:edge
    restart: "unless-stopped"
    command: zeo
    volumes:
      - ./data:/data

  instance:
    container_name: client1-mysenaite
    image: senaite/senaite:edge
    restart: "unless-stopped"
    ports:
      - "7011:8080"
    links:
      - zeo
    deploy:
      resources:
        limits:
          memory: 4GB
    environment:
      ZEO_ADDRESS: "zeo:8080"
      ADDONS: "senaite.databox senaite.patient senaite.storage"
      SOURCES: "senaite.storage=git https://github.com/senaite/senaite.storage.git branch=2.x,senaite.databox=git https://github.com/senaite/senaite.databox.git branch=master,senaite.patient=git https://github.com/senaite/senaite.patient.git branch=master"

volumes:
  data:
    external: true
```

Use these versions for Docker/Compose:

```
$ docker compose version
Docker Compose version v2.2.3
$ docker --version
Docker version 20.10.12, build e91ed57
```
